/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.CadastroDAO;
import Entidades.Pessoas;
import Util.JPAUtil;
import Util.ModeloTabela;
import Util.Util;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Klaillton
 */
public class Cadastro extends javax.swing.JFrame {

    private Pessoas pes = new Pessoas();

    private EntityManager manager = new JPAUtil().getEntityManager();

    private CadastroDAO dao = new CadastroDAO(manager);

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        codigo.setFocusCycleRoot(true);
        try {
            dtcad.setText(Util.getDate(new java.util.Date()).trim());
            preencherTabela();

        } catch (Exception e) {
            e.printStackTrace();
        }
        outroValor.setText("0,00");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        profissao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        uf = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        contr_mensal = new javax.swing.JCheckBox();
        cont_10 = new javax.swing.JRadioButton();
        cont_20 = new javax.swing.JRadioButton();
        cont_30 = new javax.swing.JRadioButton();
        cont_50 = new javax.swing.JRadioButton();
        cont_out_valor = new javax.swing.JRadioButton();
        outroValor = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaPessoas = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        expectativa = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        dtcad = new javax.swing.JFormattedTextField();
        dtnasc = new javax.swing.JFormattedTextField();
        telefone = new javax.swing.JFormattedTextField();
        celular = new javax.swing.JFormattedTextField();
        cep = new javax.swing.JFormattedTextField();
        buscarNome = new javax.swing.JButton();
        ativo = new javax.swing.JCheckBox();

        setTitle("Sócios");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Profissão:");

        jLabel4.setText("Data Cadastro:");

        jLabel5.setText("E-Mail:");

        jLabel6.setText("Tel.:");

        jLabel7.setText("Cel.:");

        jLabel8.setText("Data Nascimento:");

        jLabel9.setText("Endereço:");

        jLabel10.setText("Nº:");

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel11.setText("Bairro:");

        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });

        jLabel12.setText("CEP:");

        jLabel13.setText("Cidade:");

        jLabel14.setText("UF:");

        uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MG", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel15.setText("Contribuição:");

        contr_mensal.setText("Mensal");

        buttonGroup1.add(cont_10);
        cont_10.setSelected(true);
        cont_10.setText("R$ 10,00");
        cont_10.setActionCommand("0");
        cont_10.setFocusCycleRoot(true);
        cont_10.setNextFocusableComponent(cont_20);
        cont_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cont_10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(cont_20);
        cont_20.setText("R$ 20,00");
        cont_20.setActionCommand("1");
        cont_20.setFocusCycleRoot(true);

        buttonGroup1.add(cont_30);
        cont_30.setText("R$ 30,00");
        cont_30.setActionCommand("2");
        cont_30.setFocusCycleRoot(true);

        buttonGroup1.add(cont_50);
        cont_50.setText("R$ 50,00");
        cont_50.setActionCommand("3");
        cont_50.setFocusCycleRoot(true);

        buttonGroup1.add(cont_out_valor);
        cont_out_valor.setText("Outro Valor:");
        cont_out_valor.setActionCommand("4");
        cont_out_valor.setFocusCycleRoot(true);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        jTabelaPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabelaPessoas);

        jLabel16.setText("Expectativa de Pagamento:");

        expectativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expectativaActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        dtnasc = new JFormattedTextField(setMascara("##/##/####"));

        telefone = new JFormattedTextField(setMascara("(##) ####-####"));

        celular = new JFormattedTextField(setMascara("(##) ####-####"));
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        cep = new JFormattedTextField(setMascara("##.###-###"));

        buscarNome.setText("Buscar");
        buscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNomeActionPerformed(evt);
            }
        });

        ativo.setSelected(true);
        ativo.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(bairro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(expectativa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(celular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cont_out_valor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cont_10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cont_20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cont_30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cont_50))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(buscarNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ativo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buscar)
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dtcad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(contr_mensal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                                    .addComponent(profissao))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar)
                            .addComponent(jLabel4)
                            .addComponent(dtcad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(buscarNome)
                            .addComponent(ativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(contr_mensal)
                            .addComponent(jLabel16)
                            .addComponent(expectativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cont_10)
                            .addComponent(cont_20)
                            .addComponent(cont_30)
                            .addComponent(cont_50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cont_out_valor)
                            .addComponent(outroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar)
                            .addComponent(limpar)
                            .addComponent(excluir))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cont_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cont_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cont_10ActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:

        if (pes.getCodigo() == null || pes.getCodigo() == 0) {
            pes = new Pessoas();
        }

        String[] d = (dtnasc.getText()).split("/");
        if (d[0].equals("") || d[1].equals("") || d[2].equals("")) {
            JOptionPane.showMessageDialog(null, "A data deve ser preenchida corretamente!");

        } else {
            pes.setAtivo(ativo.isEnabled());
            pes.setNome(nome.getText());
            pes.setDataCad(Util.getDateSQL(dtcad.getText()));
            pes.setNascimento(Util.getDateSQL(dtnasc.getText()));
            pes.setProfissao(profissao.getText());
            pes.setTelefone(telefone.getText());
            pes.setBairro(bairro.getText());
            pes.setCep(cep.getText());
            pes.setCidade(cidade.getText());
            pes.setLogradouro(end.getText());
            pes.setNumero(numero.getText());
            pes.setUf(uf.getSelectedIndex() + "");
            pes.setValor(Double.parseDouble(outroValor.getText().replaceAll(",", ".")));
            pes.setEmail(email.getText());
            pes.setCont(Integer.parseInt(buttonGroup1.getSelection().getActionCommand()));
            pes.setMensal(contr_mensal.isSelected());
            pes.setExpectativa((expectativa.getText()));

            int o = JOptionPane.showConfirmDialog(this, "Deseja realmente salvar?", "Salvar", 0);

            if (o == 0) {
                
                pes = dao.salvar(pes);

                if (pes != null) {
                    LimparTela();

                    Principal p = new Principal();
                    p.preencheStatus();

                    JOptionPane.showMessageDialog(this, "Dados Salvos!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar!");
                }
            } else if (o == 1) {
                LimparTela();
            }

        }


    }//GEN-LAST:event_salvarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        LimparTela();
    }//GEN-LAST:event_limparActionPerformed

    private void LimparTela() {
        codigo.setText("");
        try {
            dtcad.setText(new Util().getDate(new java.util.Date()));
        } catch (Exception e) {
        }
        nome.setText("");
        email.setText("");
        telefone.setText("");
        profissao.setText("");
        celular.setText("");
        dtnasc.setText("");
        end.setText("");
        numero.setText("");
        bairro.setText("");
        cep.setText("");
        cidade.setText("");
        uf.setSelectedIndex(0);
        contr_mensal.setSelected(false);
        buttonGroup1.setSelected(cont_10.getModel(), true);
        outroValor.setText("0,00");
        expectativa.setText("");
        ativo.setEnabled(true);

        preencherTabela();

        pes = new Pessoas();
    }

    private void expectativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expectativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expectativaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        pes = dao.busca(Integer.parseInt(codigo.getText().trim()));

        if (pes != null) {
            codigo.setText(pes.getCodigo().toString());
            try {
                dtcad.setText(new Util().getDate(new java.util.Date()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            ativo.setEnabled(pes.getAtivo());
            nome.setText(pes.getNome());
            email.setText(pes.getEmail());
            telefone.setText(pes.getTelefone());
            profissao.setText(pes.getProfissao());
            celular.setText(pes.getTelefone());
            try {
                dtnasc.setText(Util.getDate(pes.getNascimento()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            end.setText(pes.getLogradouro());
            numero.setText(pes.getNumero());
            bairro.setText(pes.getBairro());
            cep.setText(pes.getCep());
            cidade.setText(pes.getCidade());
            uf.setSelectedIndex(pes.getUf().length());
            contr_mensal.setSelected(pes.getMensal());
            switch (pes.getCont()) {
                case 0:
                    buttonGroup1.setSelected(cont_10.getModel(), true);
                    break;
                case 1:
                    buttonGroup1.setSelected(cont_20.getModel(), true);
                    break;
                case 2:
                    buttonGroup1.setSelected(cont_30.getModel(), true);
                    break;
                case 3:
                    buttonGroup1.setSelected(cont_50.getModel(), true);
                    break;
                case 4:
                    buttonGroup1.setSelected(cont_out_valor.getModel(), true);
                    outroValor.setText(pes.getValor().toString());
                    break;
            }

            expectativa.setText(pes.getExpectativa());
        } else {
            JOptionPane.showMessageDialog(this, "Contribuinte não encontrado!");
        }

    }//GEN-LAST:event_buscarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:

        if (!"".equals(codigo.getText()) || null != codigo.getText()) {
            int o = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro?");

            if (o == 0) {
                pes = dao.busca(Integer.parseInt(codigo.getText()));
                if (pes != null) {
                    dao.delete(pes);
                    LimparTela();
                    JOptionPane.showMessageDialog(this, "Contribuinte removido com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Não foi possível remover o contribuinte!");
                }
            } else if (o == 1) {
                LimparTela();
            }

        }
    }//GEN-LAST:event_excluirActionPerformed

    private void buscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNomeActionPerformed
        // TODO add your handling code here:
        pes = dao.buscaNome(nome.getText());

        if (pes != null) {
            codigo.setText(pes.getCodigo().toString());
            try {
                dtcad.setText(new Util().getDate(new java.util.Date()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            ativo.setEnabled(pes.getAtivo());
            nome.setText(pes.getNome());
            email.setText(pes.getEmail());
            telefone.setText(pes.getTelefone());
            profissao.setText(pes.getProfissao());
            celular.setText(pes.getTelefone());
            try {
                dtnasc.setText(Util.getDate(pes.getNascimento()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            end.setText(pes.getLogradouro());
            numero.setText(pes.getNumero());
            bairro.setText(pes.getBairro());
            cep.setText(pes.getCep());
            cidade.setText(pes.getCidade());
            uf.setSelectedIndex(pes.getUf().length());
            contr_mensal.setSelected(pes.getMensal());
            switch (pes.getCont()) {
                case 0:
                    buttonGroup1.setSelected(cont_10.getModel(), true);
                    break;
                case 1:
                    buttonGroup1.setSelected(cont_20.getModel(), true);
                    break;
                case 2:
                    buttonGroup1.setSelected(cont_30.getModel(), true);
                    break;
                case 3:
                    buttonGroup1.setSelected(cont_50.getModel(), true);
                    break;
                case 4:
                    buttonGroup1.setSelected(cont_out_valor.getModel(), true);
                    outroValor.setText(pes.getValor().toString());
                    break;
            }

            expectativa.setText(pes.getExpectativa());
        } else {
            JOptionPane.showMessageDialog(this, "Contribuinte não encontrado!");
        }
    }//GEN-LAST:event_buscarNomeActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void preencherTabela() {
//        System.out.println("Preencher tabela invocado!");
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Codigo", "Nome", "Telefone", /*"Data_Cadastro",*/
            "Nascimento"/*, "Profissao", "E-Mail", "Mensal", "Valor", "CEP", "Logradouro",
            "Numero", "Bairro", "Cidade", "UF","Expectativa"*/
        };

//        System.out.println("arrayList");
//        System.out.println(SQL);
        try {

            List<Pessoas> pesList = dao.getListNamed(manager, Pessoas.FIND_ALL);
//            ResultSet pesList = (ResultSet) dao.lista();
//            pesList.first();
            for (Pessoas p : pesList) {
                dados.add(new Object[]{
                    p.getCodigo(), p.getNome(), p.getTelefone(), /*p.getDataCad(),*/ Util.getDate(p.getNascimento()), p.getProfissao(), p.getEmail(),
                    p.getMensal(), p.getValor(), p.getCep(), p.getLogradouro(), p.getNumero(), p.getBairro(), p.getCidade(), p.getUf(),
                    p.getExpectativa()

                });
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaPessoas.setModel(modelo);
        jTabelaPessoas.getColumnModel().getColumn(0).setPreferredWidth(50); //Codigo       
        jTabelaPessoas.getColumnModel().getColumn(1).setPreferredWidth(200); //Nome
        jTabelaPessoas.getColumnModel().getColumn(2).setPreferredWidth(70); //Telefone
//        jTabelaPessoas.getColumnModel().getColumn(3).setPreferredWidth(150); //Data Cadastro
        jTabelaPessoas.getColumnModel().getColumn(3).setPreferredWidth(150); //Data Nascimento
        //jTabelaPessoas.getColumnModel().getColumn(5).setPreferredWidth(480); //Profissão
        //jTabelaPessoas.getColumnModel().getColumn(6).setPreferredWidth(480); //Email
//        jTabelaPessoas.getColumnModel().getColumn(7).setPreferredWidth(480); //CEP
//        jTabelaPessoas.getColumnModel().getColumn(8).setPreferredWidth(480); //Logradouro
//        jTabelaPessoas.getColumnModel().getColumn(9).setPreferredWidth(480); //Numero da casa
//        jTabelaPessoas.getColumnModel().getColumn(10).setPreferredWidth(480); //Bairro
//        jTabelaPessoas.getColumnModel().getColumn(11).setPreferredWidth(480); //Cidade
//        jTabelaPessoas.getColumnModel().getColumn(12).setPreferredWidth(480); //UF
//        jTabelaPessoas.getColumnModel().getColumn(13).setPreferredWidth(480); //Cidade
//        jTabelaPessoas.getColumnModel().getColumn(14).setPreferredWidth(480); //Mensalista
//        jTabelaPessoas.getColumnModel().getColumn(15).setPreferredWidth(480); //Valores Padrao
//        jTabelaPessoas.getColumnModel().getColumn(16).setPreferredWidth(480); //Valor não padrão
//        jTabelaPessoas.getColumnModel().getColumn(17).setPreferredWidth(480); //Expectativa

        jTabelaPessoas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTabelaPessoas.getTableHeader().setReorderingAllowed(false);
        jTabelaPessoas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    }

    private MaskFormatter setMascara(String mascara) {
        MaskFormatter mask = null;
        try {
            mask = new MaskFormatter(mascara);
        } catch (java.text.ParseException ex) {
        }
        return mask;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativo;
    private javax.swing.JTextField bairro;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarNome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField codigo;
    private javax.swing.JRadioButton cont_10;
    private javax.swing.JRadioButton cont_20;
    private javax.swing.JRadioButton cont_30;
    private javax.swing.JRadioButton cont_50;
    private javax.swing.JRadioButton cont_out_valor;
    private javax.swing.JCheckBox contr_mensal;
    private javax.swing.JFormattedTextField dtcad;
    private javax.swing.JFormattedTextField dtnasc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField end;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField expectativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaPessoas;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField outroValor;
    private javax.swing.JTextField profissao;
    private javax.swing.JButton salvar;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JComboBox<String> uf;
    // End of variables declaration//GEN-END:variables
}
