/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.CadastroDAO;
import DAO.PagamentoDAO;
import Entidades.Pagamento;
import Entidades.Pessoas;
import Util.JPAUtil;
import Util.UtCodigo;
import Util.Util;
import java.util.Date;
import java.util.UUID;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;

/**
 *
 * @author Klaillton
 */
public class PagamentoTela extends javax.swing.JFrame {

    private EntityManager manager = new JPAUtil().getEntityManager();

    private Pessoas pes = new Pessoas();

    private Entidades.Pagamento pag = new Entidades.Pagamento();

    private PagamentoDAO pagdao = new PagamentoDAO(manager);

    private CadastroDAO dao = new CadastroDAO(manager);

    /**
     * Creates new form Pagamento
     */
    public PagamentoTela() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        Confirmar = new javax.swing.JButton();
        cont_10 = new javax.swing.JRadioButton();
        cont_20 = new javax.swing.JRadioButton();
        cont_30 = new javax.swing.JRadioButton();
        cont_50 = new javax.swing.JRadioButton();
        cont_out_valor = new javax.swing.JRadioButton();
        outroValor = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();

        setTitle("Doações");

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel4.setText("Telefone:");

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        buttonGroup1.add(cont_10);
        cont_10.setSelected(true);
        cont_10.setText("R$ 10,00");
        cont_10.setActionCommand("0");
        cont_10.setFocusCycleRoot(true);
        cont_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cont_10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(cont_20);
        cont_20.setText("R$ 20,00");
        cont_20.setActionCommand("1");
        cont_20.setFocusCycleRoot(true);

        buttonGroup1.add(cont_30);
        cont_30.setText("R$ 30,00");
        cont_30.setActionCommand("2");
        cont_30.setFocusCycleRoot(true);

        buttonGroup1.add(cont_50);
        cont_50.setText("R$ 50,00");
        cont_50.setActionCommand("3");
        cont_50.setFocusCycleRoot(true);

        buttonGroup1.add(cont_out_valor);
        cont_out_valor.setText("Outro Valor:");
        cont_out_valor.setActionCommand("4");
        cont_out_valor.setFocusCycleRoot(true);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Buscar))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cont_out_valor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cont_10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cont_20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cont_30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cont_50))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Confirmar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cont_10)
                    .addComponent(cont_20)
                    .addComponent(cont_30)
                    .addComponent(cont_50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cont_out_valor)
                    .addComponent(outroValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(Confirmar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cont_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cont_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cont_10ActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed

        Pagamento pago = new Pagamento();
        Pessoas p = new Pessoas();

        if (pes.getNome() != null) {

//            manager.persist(pes);
            p = manager.find(Pessoas.class, Integer.parseInt(codigo.getText()));

            manager.persist(p);

            pago.setPessoas(p);

            try {
                pago.setDataPag(new Date());

                pago.setCont(Integer.parseInt(buttonGroup1.getSelection().getActionCommand()));
                if (Integer.parseInt(buttonGroup1.getSelection().getActionCommand()) == 4) {
                    pago.setValor(Double.parseDouble(outroValor.getText().replaceAll(",", ".")));
                } else {
                    switch (Integer.parseInt(buttonGroup1.getSelection().getActionCommand())) {
                        case 0:
                            pago.setValor(Double.parseDouble("10.00"));
                            break;
                        case 1:
                            pago.setValor(Double.parseDouble("20.00"));
                            break;
                        case 2:
                            pago.setValor(Double.parseDouble("30.00"));
                            break;
                        case 3:
                            pago.setValor(Double.parseDouble("50.00"));
                            break;

                    }

                }
                //pago.setIdentificador(UtCodigo.getCodigoVerificacao(pes.getCodigo().toString(), pes.getNome()));
                final String uuid = UUID.randomUUID().toString().replaceAll("-", "")+pes.getCodigo().toString();
                System.out.println("uuid = " + uuid.substring(15).toUpperCase());
                pago.setIdentificador(uuid.substring(15).toUpperCase());
                System.out.println("Identificador: " + pago.getIdentificador());
                System.out.println("Pessoas.codigo: " + pago.getPessoas().getCodigo());

                int o = JOptionPane.showConfirmDialog(this, "Deseja realmente salvar?", "Salvar", 0);

                if (o == 0) {
                    pag = pagdao.salvar(pago);

                    if (pag.getCodigo() != null) {
                        JOptionPane.showMessageDialog(this, "Pagamento salvo com sucesso!");
                        pes = new Pessoas();
                        pag = new Pagamento();
                        limparTela();

                    } else {
                        JOptionPane.showMessageDialog(this, "Ocorreu um erro ao registrar o pagamento - Código: 1");
                    }
                } else {
                    limparTela();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao registrar o pagamento - Código: 2");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "É necessário um contribuinte para realizar o pagamento");
        }

    }//GEN-LAST:event_ConfirmarActionPerformed

    private void limparTela() {
        codigo.setText("");
        buttonGroup1.setSelected(cont_10.getModel(), true);
        outroValor.setText("");
        nome.setText("");
        telefone.setText("");
    }

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        pes = dao.busca(Integer.parseInt(codigo.getText().trim()));

        if (pes != null) {
            codigo.setText(pes.getCodigo().toString());
            nome.setText(pes.getNome());
            switch (pes.getCont()) {
                case 0:
                    buttonGroup1.setSelected(cont_10.getModel(), true);
                    break;
                case 1:
                    buttonGroup1.setSelected(cont_20.getModel(), true);
                    break;
                case 2:
                    buttonGroup1.setSelected(cont_30.getModel(), true);
                    break;
                case 3:
                    buttonGroup1.setSelected(cont_50.getModel(), true);
                    break;
                case 4:
                    buttonGroup1.setSelected(cont_out_valor.getModel(), true);
                    outroValor.setText(pes.getValor().toString());
                    break;
                default:
                    buttonGroup1.setSelected(cont_10.getModel(), true);
            }

            telefone.setText(pes.getTelefone());
        } else {
            limparTela();
            JOptionPane.showMessageDialog(this, "Contribuinte não encontrado!");
        }
    }//GEN-LAST:event_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Confirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigo;
    private javax.swing.JRadioButton cont_10;
    private javax.swing.JRadioButton cont_20;
    private javax.swing.JRadioButton cont_30;
    private javax.swing.JRadioButton cont_50;
    private javax.swing.JRadioButton cont_out_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField outroValor;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
