/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.UsuarioDAO;
import Entidades.Usuario;
import Util.JPAUtil;
import Util.ModeloTabela;
import Util.Util;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Klaillton
 */
public class User extends javax.swing.JFrame {

    private Usuario pes = new Usuario();

    private EntityManager manager = new JPAUtil().getEntityManager();

    private UsuarioDAO dao = new UsuarioDAO(manager);

    private boolean travaLogin = false;

    /**
     * Creates new form Usuario
     */
    public User() {
        initComponents();
        preencherTabela();
        try {
            dtcad.setText(Util.getDate(new java.util.Date()).trim());
            preencherTabela();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        bairro = new javax.swing.JTextField();
        dtcad = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        dtnasc = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        cidade = new javax.swing.JTextField();
        celular = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        cep = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        uf = new javax.swing.JComboBox<>();
        buscarNome = new javax.swing.JButton();
        codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ativo = new javax.swing.JCheckBox();
        profissao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaUsuario = new javax.swing.JTable();
        salvar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        confirmaSenha = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();

        setTitle("Usuarios");

        jLabel6.setText("Tel.:");

        jLabel7.setText("Cel.:");

        jLabel8.setText("Data Nascimento:");

        jLabel9.setText("Endereço:");

        jLabel10.setText("Nº:");

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        jLabel11.setText("Bairro:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });

        jLabel12.setText("CEP:");

        dtnasc = new JFormattedTextField(setMascara("##/##/####"));

        jLabel13.setText("Cidade:");

        telefone = new JFormattedTextField(setMascara("(##) ####-####"));

        celular = new JFormattedTextField(setMascara("(##) ####-####"));
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        jLabel14.setText("UF:");

        cep = new JFormattedTextField(setMascara("##.###-###"));

        jLabel1.setText("Codigo:");

        uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MG", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        buscarNome.setText("Buscar");
        buscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Profissão:");

        ativo.setSelected(true);
        ativo.setText("Ativo");

        jLabel4.setText("Data Cadastro:");

        jLabel5.setText("E-Mail:");

        jTabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabelaUsuario);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        jLabel15.setText("Senha:");

        jLabel16.setText("Confirmar:");

        jLabel17.setText("Login:");

        login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(buscarNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ativo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtcad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(email)
                                    .addComponent(profissao, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(228, 228, 228)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(salvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(limpar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(excluir))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(27, 27, 27)
                            .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(senha, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(login))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(22, 22, 22)
                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar)
                            .addComponent(jLabel4)
                            .addComponent(dtcad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(buscarNome)
                            .addComponent(ativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(profissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar)
                            .addComponent(limpar)
                            .addComponent(excluir)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        pes = dao.busca(Integer.parseInt(codigo.getText().trim()));

        if (pes != null) {
            codigo.setText(pes.getCodigo().toString());
            try {
                dtcad.setText(new Util().getDate(new java.util.Date()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            ativo.setEnabled(pes.isAtivo());
            nome.setText(pes.getNome());
            email.setText(pes.getEmail());
            telefone.setText(pes.getTelefone());
            profissao.setText(pes.getProfissao());
            celular.setText(pes.getTelefone());
            try {
                dtnasc.setText(Util.getDate(pes.getNascimento()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            end.setText(pes.getLogradouro());
            numero.setText(pes.getNumero());
            bairro.setText(pes.getBairro());
            cep.setText(pes.getCep());
            cidade.setText(pes.getCidade());
            uf.setSelectedIndex(pes.getUf().length());
            login.setText(pes.getLogin());
        } else {
            JOptionPane.showMessageDialog(this, "Contribuinte não encontrado!");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void buscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNomeActionPerformed
        // TODO add your handling code here:
        pes = dao.buscaNome(nome.getText());

        if (pes != null) {
            codigo.setText(pes.getCodigo().toString());
            try {
                dtcad.setText(new Util().getDate(new java.util.Date()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            ativo.setEnabled(pes.isAtivo());
            nome.setText(pes.getNome());
            email.setText(pes.getEmail());
            telefone.setText(pes.getTelefone());
            profissao.setText(pes.getProfissao());
            celular.setText(pes.getTelefone());
            try {
                dtnasc.setText(Util.getDate(pes.getNascimento()));
            } catch (Exception e) {
                e.printStackTrace();
            }
            end.setText(pes.getLogradouro());
            numero.setText(pes.getNumero());
            bairro.setText(pes.getBairro());
            cep.setText(pes.getCep());
            cidade.setText(pes.getCidade());
            uf.setSelectedIndex(pes.getUf().length());
            login.setText(pes.getLogin());
        } else {
            JOptionPane.showMessageDialog(this, "Contribuinte não encontrado!");
        }
    }//GEN-LAST:event_buscarNomeActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:

        if (pes.getCodigo() == null || pes.getCodigo() == 0) {
            pes = new Usuario();
        }

        String[] d = (dtnasc.getText()).split("/");
        if (d[0].equals("") || d[1].equals("") || d[2].equals("")) {
            JOptionPane.showMessageDialog(null, "A data deve ser preenchida corretamente!");

        } else if (travaLogin) {
            JOptionPane.showMessageDialog(this, "Este login já está sendo utilizado!");
        } else {
            pes.setAtivo(ativo.isEnabled());
            pes.setNome(nome.getText());
            pes.setDataCad(Util.getDateSQL(dtcad.getText()));
            pes.setNascimento(Util.getDateSQL(dtnasc.getText()));
            pes.setProfissao(profissao.getText());
            pes.setTelefone(telefone.getText());
            pes.setCelular(celular.getText());
            pes.setBairro(bairro.getText());
            pes.setCep(cep.getText());
            pes.setCidade(cidade.getText());
            pes.setLogradouro(end.getText());
            pes.setNumero(numero.getText());
            pes.setUf(uf.getSelectedIndex() + "");
            pes.setEmail(email.getText());
            pes.setLogin(login.getText());
            pes.setSenha(new String(senha.getPassword()));

            int o = JOptionPane.showConfirmDialog(this, "Deseja realmente salvar?", "Salvar", 0);

            if (o == 0) {

                if (Arrays.toString(confirmaSenha.getPassword()).
                        equals(Arrays.toString(senha.getPassword()))) {
                    pes = dao.salvar(pes);
                    if (pes != null) {
                        LimparTela();

                        Principal p = new Principal();
                        p.preencheStatus();

                        JOptionPane.showMessageDialog(this, "Dados Salvos!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao salvar!");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "As senhas não correspondem!");
                }

            } else {
                LimparTela();
            }

        }

    }//GEN-LAST:event_salvarActionPerformed

    private void LimparTela() {
        codigo.setText("");
        try {
            dtcad.setText(new Util().getDate(new java.util.Date()));
        } catch (Exception e) {
        }
        nome.setText("");
        email.setText("");
        telefone.setText("");
        profissao.setText("");
        celular.setText("");
        dtnasc.setText("");
        end.setText("");
        numero.setText("");
        bairro.setText("");
        cep.setText("");
        cidade.setText("");
        uf.setSelectedIndex(0);
        ativo.setEnabled(true);
        login.setText("");
        senha.setText("");
        confirmaSenha.setText("");

        preencherTabela();

        pes = new Usuario();
    }

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        LimparTela();
    }//GEN-LAST:event_limparActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:

        if (!"".equals(codigo.getText()) || null != codigo.getText()) {
            int o = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro?");

            if (o == 0) {
                pes = dao.busca(Integer.parseInt(codigo.getText()));
                if (pes != null) {
                    dao.delete(pes);
                    LimparTela();
                    JOptionPane.showMessageDialog(this, "Contribuinte removido com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Não foi possível remover o contribuinte!");
                }
            } else if (o == 1) {
                LimparTela();
            }

        }
    }//GEN-LAST:event_excluirActionPerformed

    private void loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFocusLost
        // TODO add your handling code here:
        if (dao.buscaUsuario(login.getText()) != null) {
            travaLogin = true;
            JOptionPane.showMessageDialog(this, "Este Login já está sendo usado, por favor escolha outro!");
        } else {
            travaLogin = false;
        }
    }//GEN-LAST:event_loginFocusLost

    private void preencherTabela() {
//        System.out.println("Preencher tabela invocado!");
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Codigo", "Nome", "Login", /*"Data_Cadastro",
            "Nascimento"/*, "Profissao", "E-Mail", "Mensal", "Valor", "CEP", "Logradouro",
            "Numero", "Bairro", "Cidade", "UF","Expectativa"*/};

//        System.out.println("arrayList");
//        System.out.println(SQL);
        try {

            List<Usuario> pesList = dao.getListNamed(manager, Usuario.FIND_ALL);
//            ResultSet pesList = (ResultSet) dao.lista();
//            pesList.first();
            for (Usuario p : pesList) {
                dados.add(new Object[]{
                    p.getCodigo(), p.getNome(), p.getLogin(), /*p.getDataCad(), Util.getDate(p.getNascimento()), p.getProfissao(), p.getEmail(),
                    /*p.getMensal(), p.getValor(), p.getCep(), p.getLogradouro(), p.getNumero(), p.getBairro(), p.getCidade(), p.getUf(),
                    /*p.getExpectativa()*/});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }

        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTabelaUsuario.setModel(modelo);
        jTabelaUsuario.getColumnModel().getColumn(0).setPreferredWidth(50); //Codigo       
        jTabelaUsuario.getColumnModel().getColumn(1).setPreferredWidth(230); //Nome
        jTabelaUsuario.getColumnModel().getColumn(2).setPreferredWidth(70); //login
//        jTabelaUsuario.getColumnModel().getColumn(3).setPreferredWidth(150); //Data Cadastro
//        jTabelaUsuario.getColumnModel().getColumn(3).setPreferredWidth(150); //Data Nascimento
        //jTabelaUsuario.getColumnModel().getColumn(5).setPreferredWidth(480); //Profissão
        //jTabelaUsuario.getColumnModel().getColumn(6).setPreferredWidth(480); //Email
//        jTabelaUsuario.getColumnModel().getColumn(7).setPreferredWidth(480); //CEP
//        jTabelaUsuario.getColumnModel().getColumn(8).setPreferredWidth(480); //Logradouro
//        jTabelaUsuario.getColumnModel().getColumn(9).setPreferredWidth(480); //Numero da casa
//        jTabelaUsuario.getColumnModel().getColumn(10).setPreferredWidth(480); //Bairro
//        jTabelaUsuario.getColumnModel().getColumn(11).setPreferredWidth(480); //Cidade
//        jTabelaUsuario.getColumnModel().getColumn(12).setPreferredWidth(480); //UF
//        jTabelaUsuario.getColumnModel().getColumn(13).setPreferredWidth(480); //Cidade
//        jTabelaUsuario.getColumnModel().getColumn(14).setPreferredWidth(480); //Mensalista
//        jTabelaUsuario.getColumnModel().getColumn(15).setPreferredWidth(480); //Valores Padrao
//        jTabelaUsuario.getColumnModel().getColumn(16).setPreferredWidth(480); //Valor não padrão
//        jTabelaUsuario.getColumnModel().getColumn(17).setPreferredWidth(480); //Expectativa

        jTabelaUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTabelaUsuario.getTableHeader().setReorderingAllowed(false);
        jTabelaUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    }

    private MaskFormatter setMascara(String mascara) {
        MaskFormatter mask = null;
        try {
            mask = new MaskFormatter(mascara);
        } catch (java.text.ParseException ex) {
        }
        return mask;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativo;
    private javax.swing.JTextField bairro;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscarNome;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField codigo;
    private javax.swing.JPasswordField confirmaSenha;
    private javax.swing.JFormattedTextField dtcad;
    private javax.swing.JFormattedTextField dtnasc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField end;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaUsuario;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField profissao;
    private javax.swing.JButton salvar;
    private javax.swing.JPasswordField senha;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JComboBox<String> uf;
    // End of variables declaration//GEN-END:variables
}
